# daybook-secret.yaml
# This is Example we actually don't push this but for reference i have pushed it.
# Chnage the values accrodingly.
apiVersion: v1
kind: Secret
metadata:
  name: daybook-secret
type: Opaque
stringData:
  MONGO_USERNAME: ""
  MONGO_PASSWORD: ""
  JWT_SECRET: "supersecretjwtkey"
